#.py file to load a tensor generated by generateTensor.py 

import torch 
import cv2
import numpy as np

print('--- program starts here ---')

T=torch.load("T.pt",weights_only=True)
print("Tensor loaded!")

dimT=T.shape
print("T has",dimT[1],"persons, each person has",dimT[2],"poses, each pose is a picture with",dimT[0],"elements.")

print('--- program ends here ---')



#TESTS
originalheight=192
originalwidth=168
factor=3
height=int(originalheight/factor)
width=int(originalwidth/factor)
print("T[:,-1,-1]=",T[:,-1,-1])
A=T[:,-1,-1]
A=torch.reshape(A,(height,width))
print("A=",A)
a=A.numpy()
print("a=", a)
print("a shape=", a.shape)
cv2.imshow("a",a)
cv2.waitKey(1500)



